[variables]
PORT = "3000"

[build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "python app.py"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmd = "pip install --no-cache-dir -r requirements.txt"
